# Generated by Django 2.0.13 on 2019-08-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20190828_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
