# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-30 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('items', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='restaurant.User')),
            ],
            options={
                'verbose_name_plural': 'CartItems',
                'verbose_name': 'CartItem',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('restaurant', models.CharField(max_length=500)),
                ('items', models.ManyToManyField(blank=True, related_name='order', to='restaurant.CartItems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='restaurant.User')),
            ],
            options={
                'verbose_name_plural': 'Oredrs',
                'verbose_name': 'Order',
            },
        ),
    ]
